version: '3'

services:
  test_ps:
    hostname: test_ps
    container_name: test_ps
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4554:4554
    environment:
      - PORT=4554
      - REDIS_URL=redis://redis:6379
      - TP_SERVER=http://tp:9765  

    networks:
      - ps_default
      - tp_default
      - redis_db

networks:
  tp_default:
    external:
      name: tp_default
  redis_db:
    external:
      name: redis_db
  ps_default:
    driver: bridge
    name: test_ps_default
