version: '3'

services:
  ps:
    container_name: ps
    hostname: PS
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6002:6002
    environment:
      PORT: 6002
      REDIS_URL: redis://redis:6379/3
      BS_URL: http://BS:6001
      PS_URL: http://PS:6002
      UA_URL: http://UA:6003
      TP_URL: http://TP:6004
    networks:
      - ps_net
      - bs_net
      - tp_net
      - ua_net
      - redis_db

networks:
  ps_net:
    driver: bridge
    name: ps_net
  tp_net:
    external: true
    name: tp_net
  ua_net:
    external: true
    name: ua_net
  bs_net:
    external: true
    name: bs_net
  redis_db:
    external: true
    name: redis_db
